### ISSUE TITLE
Not able to compile

### ISSUE THREAD

**Issue by aniketroxx** [anderson-joyle/D365O-Addins#19]
Hi,
I was trying to build my own add-in and problem seems to be that i am always getting these error whenever i change code and there seems to be no clue to me what to do.

![image](https://user-images.githubusercontent.com/6142430/45596433-89752e00-b9d9-11e8-9a78-fc37e7838f69.png)

**Comment by TrudAX** [comment]
Try to delete the file in destination folder manually. In most cases you need to close VS to do this

**Comment by anderson-joyle** [comment]
@aniketroxx let us know if this fixed you problem so I can close this issue.

**Comment by aniketroxx** [comment]
Hi Do we have proper way for this ? Because debugging seems to be a huge issue . 

@TrudAX  Destination folder you mean VS/Project/Debug or where its trying to copy ?

**Comment by anderson-joyle** [comment]
What "proper way" means? What are you trying to debbug?
Error message is showing destination folder:
C:\\PROGRAM FILES (X86)\MICOSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\12x0luh1.5MM...
Dont forget to close all instances of VS.

**Comment by aniketroxx** [comment]
@anderson-joyle  Means why we need to delete and restart VS everytime . I think there must be some proper MS way. This deleting file closing and opening seems like hack but anyways thanks for that . You can close this issue if we don't have any more information on this.

**Comment by anderson-joyle** [comment]
Not sure if there is any other way. Problem is, when you open VS, it "locks" extension dlls from extension folder. We can say its the same thing if you try to delete a Word document while open.
